#!/bin/bash
set -eu -o pipefail
set -f
readonly DIR=$(dirname "$0")
cd "${DIR}"
#END

curl -L https://sw.kovidgoyal.net/kitty/installer.sh | sh /dev/stdin
pip install Pygments
ln -s ~/.local/kitty.app/bin/kitty ~/.local/bin/
cp ~/.local/kitty.app/share/applications/kitty.desktop ~/.local/share/applications
sed -i "s/Icon\=kitty/Icon\=\/home\/$USER\/.local\/kitty.app\/share\/icons\/hicolor\/256x256\/apps\/kitty.png/" ~/.local/share/applications/kitty.desktop
sed -i "s/^Exec\=kitty/Exec\=kitty -1 \/bin\/sh -c \"\/usr\/local\/bin\/tmux a -t default \|\| tmux new -s default\"/" ~/.local/share/applications/kitty.desktop

