#!/bin/bash
set -eu -o pipefail
set -f
readonly DIR=$(dirname "$0")
cd "${DIR}"
#END

sudo apt-get install libncurses5-dev libncursesw5-dev libevent-dev bison flex urlview gawk
CHECKOUT=3.0a
git clone --branch "${CHECKOUT}" --depth 1 https://github.com/tmux/tmux.git repo
cd repo
sh autogen.sh
./configure && make
sudo make install

sudo ln -s "${DIR}/bash_completion_tmux.sh" /etc/bash_completion.d/tmux.sh

CHECKOUT=0.9.2
git clone --branch "${CHECKOUT}" --depth 1 https://github.com/facebook/PathPicker.git path-picker
ln -s "${DIR}/path-picker/fpp" ../../bin/fpp
 
