#!/bin/bash
set -eu -o pipefail
set -f
readonly DIR=$(dirname \"$0\")
cd \"${DIR}\"
#END

curl -O https://download.clojure.org/install/linux-install-1.10.1.492.sh
chmod +x linux-install-1.10.1.492.sh
sudo ./linux-install-1.10.1.492.sh
rm linux-install-1.10.1.492.sh
